version: ''
services:
  Service1:
    image: 
    build: ./Service1 
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 1
    depends_on:
      - database  
  Service2:
    image:      
    build: ./Service2
    ports:
    - target: 5001
      protocol: tcp
    deploy:
      replicas: 1
  Service3:    
    image: 
    build: ./Service3 
    ports:
    - target: 5002
      protocol: tcp
    deploy:
      replicas: 1  
  Service4:
    image: 
    build: ./Service4
    ports:
    - target: 5003
      protocol: tcp
    deploy:
      replicas: 1
  database:
    image: 
    build: 
    ports:
    